### ISSUE TITLE
Extract the custom mesh 

### ISSUE THREAD

**Issue by lazyDamon** [IVRL/VolRecon#4]
Hi, thank you for your great work! On dtu datasets, it looks good. I try to extract the mesh on custom datasets. First, I use `script/eval_general.sh` to rendering image and depth. Then I try to run `tsdf_fusion.sh` to get the reconstructed meshes. Finally, I changed the image shape and view list to my own datasets in `evaluation/clean_mesh.py`. But results are badly. Here are some of my results, hope you can help me, thank you!
![00000083](https://github.com/IVRL/VolRecon/assets/80307839/16bbe1b3-5d2b-4994-b6f8-93430ed7a95a)
![tsdf](https://github.com/IVRL/VolRecon/assets/80307839/30ea47f1-c31d-40eb-8c7e-05a8f8fb0007)
![clean_mesh1](https://github.com/IVRL/VolRecon/assets/80307839/cf231264-4c8e-4176-8d47-5896ae84edc9)
![clean_mesh2](https://github.com/IVRL/VolRecon/assets/80307839/6d163216-0afe-4340-bb46-c760e6ec9e95)

**Comment by FangjinhuaWang** [comment]
Since VolRecon is able to render depth with good quality on ETH3D, it should have good generalization ability. Since your mesh looks very coarse, I think the problem may come from tsdf_fusion. First, I think you can check whether rendered depth maps look reasonable. Second, I think you need to tune 'voxel_size' in tsdf_fusion.sh. On DTU, voxel_size is set to 1.5 (the metric is millimeter). You need to adjust it based on your scale and metric (meter or millimeter).
