### ISSUE TITLE
camera coordinate in data preprocessing (dtu_train.py)

### ISSUE THREAD

**Issue by youngju-na** [IVRL/VolRecon#7]
Hi! First of all, thanks for sharing this great work!
I assume that you are busy, but I have trivial questions about the camera matrix in dtu_train.py.

When you define w2c matrix in _Line 270 of dtu_train.py_, why do we need to multiply w2c_ref_inv matrix to all extrinsics?
`w2cs.append(self.all_extrinsics[index_mat] @ w2c_ref_inv)` 
instead of simply using `self.all_extrinsics[index_mat]`?

I think this is because we need to make sample['ray_o'] defined in world coordinates like below.
`sample['ref_pose']         = (intrinsics_pad @ sample['w2cs'])[0]`
`sample['ray_o'] = sample['ref_pose_inv'][:3,-1]`

Am I correct here?

In addition, what is self.homo_pixel for? I assume that it is used to make ray_d in camera coordinate, but I am confused here.

Again, thanks for sharing the work and answering questions.

**Comment by ryf1123** [comment]
Hi, sorry for my late reply! 

The difference between `w2cs.append(self.all_extrinsics[index_mat] @ w2c_ref_inv)` and `self.all_extrinsics[index_mat]` is the choice of world coordinate. In `w2cs.append(self.all_extrinsics[index_mat] @ w2c_ref_inv)` case, we are using the reference view coordinate system instead of DTU's world coordinate system. 

As defined in the `__init__` method, `self.homo_pixel` is a coordinate of the image plane `np.meshgrid` but extended to 3rd dimension representing the z-value (all 1).

**Comment by ryf1123** [comment]
Feel free to reopen this issue
